package info.xudshen.jandan.data.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import info.xudshen.jandan.domain.model.Meta;
import info.xudshen.jandan.domain.model.Post;
import info.xudshen.jandan.domain.model.SimplePost;
import info.xudshen.jandan.domain.model.Author;
import info.xudshen.jandan.domain.model.Category;
import info.xudshen.jandan.domain.model.Comment;
import info.xudshen.jandan.domain.model.ReadLaterItem;

import info.xudshen.jandan.data.dao.MetaDao;
import info.xudshen.jandan.data.dao.PostDao;
import info.xudshen.jandan.data.dao.SimplePostDao;
import info.xudshen.jandan.data.dao.AuthorDao;
import info.xudshen.jandan.data.dao.CategoryDao;
import info.xudshen.jandan.data.dao.CommentDao;
import info.xudshen.jandan.data.dao.ReadLaterItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    public DaoSession setContext(Context context) {
        metaDao.setContext(context);
        postDao.setContext(context);
        simplePostDao.setContext(context);
        authorDao.setContext(context);
        categoryDao.setContext(context);
        commentDao.setContext(context);
        readLaterItemDao.setContext(context);
        return this;
    }

    private final DaoConfig metaDaoConfig;
    private final DaoConfig postDaoConfig;
    private final DaoConfig simplePostDaoConfig;
    private final DaoConfig authorDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig commentDaoConfig;
    private final DaoConfig readLaterItemDaoConfig;

    private final MetaDao metaDao;
    private final PostDao postDao;
    private final SimplePostDao simplePostDao;
    private final AuthorDao authorDao;
    private final CategoryDao categoryDao;
    private final CommentDao commentDao;
    private final ReadLaterItemDao readLaterItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        metaDaoConfig = daoConfigMap.get(MetaDao.class).clone();
        metaDaoConfig.initIdentityScope(type);

        postDaoConfig = daoConfigMap.get(PostDao.class).clone();
        postDaoConfig.initIdentityScope(type);

        simplePostDaoConfig = daoConfigMap.get(SimplePostDao.class).clone();
        simplePostDaoConfig.initIdentityScope(type);

        authorDaoConfig = daoConfigMap.get(AuthorDao.class).clone();
        authorDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        readLaterItemDaoConfig = daoConfigMap.get(ReadLaterItemDao.class).clone();
        readLaterItemDaoConfig.initIdentityScope(type);

        metaDao = new MetaDao(metaDaoConfig, this);
        postDao = new PostDao(postDaoConfig, this);
        simplePostDao = new SimplePostDao(simplePostDaoConfig, this);
        authorDao = new AuthorDao(authorDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);
        readLaterItemDao = new ReadLaterItemDao(readLaterItemDaoConfig, this);

        registerDao(Meta.class, metaDao);
        registerDao(Post.class, postDao);
        registerDao(SimplePost.class, simplePostDao);
        registerDao(Author.class, authorDao);
        registerDao(Category.class, categoryDao);
        registerDao(Comment.class, commentDao);
        registerDao(ReadLaterItem.class, readLaterItemDao);
    }
    
    public void clear() {
        metaDaoConfig.getIdentityScope().clear();
        postDaoConfig.getIdentityScope().clear();
        simplePostDaoConfig.getIdentityScope().clear();
        authorDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        commentDaoConfig.getIdentityScope().clear();
        readLaterItemDaoConfig.getIdentityScope().clear();
    }

    public MetaDao getMetaDao() {
        return metaDao;
    }

    public PostDao getPostDao() {
        return postDao;
    }

    public SimplePostDao getSimplePostDao() {
        return simplePostDao;
    }

    public AuthorDao getAuthorDao() {
        return authorDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public ReadLaterItemDao getReadLaterItemDao() {
        return readLaterItemDao;
    }

}
