package info.xudshen.jandan.domain.model;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import android.databinding.Bindable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "AUTHOR".
 */
public class Author {

    private Long id;
    @Expose
    @SerializedName("id")
    private Long authorId;
    @Expose
    private String slug;
    @Expose
    private String name;
    @Expose
    private String firstName;
    @Expose
    private String lastName;
    @Expose
    private String nickName;
    @Expose
    private String url;
    @Expose
    private String description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Author() {
    }

    public Author(Long id) {
        this.id = id;
    }

    public Author(Long id, Long authorId, String slug, String name, String firstName, String lastName, String nickName, String url, String description) {
        this.id = id;
        this.authorId = authorId;
        this.slug = slug;
        this.name = name;
        this.firstName = firstName;
        this.lastName = lastName;
        this.nickName = nickName;
        this.url = url;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAuthorId() {
        return authorId;
    }

    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
