package info.xudshen.jandan.domain.model;

import com.google.gson.annotations.Expose;
import android.databinding.Bindable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "AUTHOR".
 */
public class Author {

    private Long id;
    @Expose
    private Long authorId;
    @Expose
    private String slug;
    @Expose
    private String name;
    @Expose
    private String first_name;
    @Expose
    private String last_name;
    @Expose
    private String nick_name;
    @Expose
    private String url;
    @Expose
    private String description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Author() {
    }

    public Author(Long id) {
        this.id = id;
    }

    public Author(Long id, Long authorId, String slug, String name, String first_name, String last_name, String nick_name, String url, String description) {
        this.id = id;
        this.authorId = authorId;
        this.slug = slug;
        this.name = name;
        this.first_name = first_name;
        this.last_name = last_name;
        this.nick_name = nick_name;
        this.url = url;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAuthorId() {
        return authorId;
    }

    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFirst_name() {
        return first_name;
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public String getLast_name() {
        return last_name;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    public String getNick_name() {
        return nick_name;
    }

    public void setNick_name(String nick_name) {
        this.nick_name = nick_name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
