package info.xudshen.jandan.domain.model;

import com.google.gson.annotations.Expose;
import android.databinding.Bindable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "META".
 */
public class Meta {

    private Long id;
    @Expose
    private Long postPage;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Meta() {
    }

    public Meta(Long id) {
        this.id = id;
    }

    public Meta(Long id, Long postPage) {
        this.id = id;
        this.postPage = postPage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPostPage() {
        return postPage;
    }

    public void setPostPage(Long postPage) {
        this.postPage = postPage;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
