package info.xudshen.jandan.domain.model;

import com.google.gson.annotations.Expose;
import java.sql.Timestamp;
import android.databinding.Bindable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "META".
 */
public class Meta {

    private Long id;
    @Expose
    private String key;
    @Expose
    private String value;
    @Expose
    private Long longValue;
    @Expose
    private Timestamp timeValue;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Meta() {
    }

    public Meta(Long id) {
        this.id = id;
    }

    public Meta(Long id, String key, String value, Long longValue, Timestamp timeValue) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.longValue = longValue;
        this.timeValue = timeValue;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Long getLongValue() {
        return longValue;
    }

    public void setLongValue(Long longValue) {
        this.longValue = longValue;
    }

    public Timestamp getTimeValue() {
        return timeValue;
    }

    public void setTimeValue(Timestamp timeValue) {
        this.timeValue = timeValue;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
