package info.xudshen.jandan.domain.model;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import java.sql.Timestamp;
import android.databinding.Bindable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PIC_ITEM".
 */
public class PicItem {

    private Long id;
    @Expose
    @SerializedName("comment_ID")
    private Long picId;
    @Expose
    @SerializedName("comment_author")
    private String author;
    @Expose
    @SerializedName("comment_author_email")
    private String authorEmail;
    @Expose
    @SerializedName("comment_author_url")
    private String authorUrl;
    @Expose
    @SerializedName("comment_date")
    private Timestamp date;
    @Expose
    private Long votePositive;
    @Expose
    private Long voteNegative;
    @Expose
    private Long commentCount;
    @Expose
    private String threadId;
    @Expose
    @SerializedName("comment_content")
    private String content;
    @Expose
    @SerializedName("text_content")
    private String textContent;
    
    private String pics;
    @Expose
    private String picFirst;
    @Expose
    private Long picCount;
    @Expose
    private Boolean hasGif;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PicItem() {
    }

    public PicItem(Long id) {
        this.id = id;
    }

    public PicItem(Long id, Long picId, String author, String authorEmail, String authorUrl, Timestamp date, Long votePositive, Long voteNegative, Long commentCount, String threadId, String content, String textContent, String pics, String picFirst, Long picCount, Boolean hasGif) {
        this.id = id;
        this.picId = picId;
        this.author = author;
        this.authorEmail = authorEmail;
        this.authorUrl = authorUrl;
        this.date = date;
        this.votePositive = votePositive;
        this.voteNegative = voteNegative;
        this.commentCount = commentCount;
        this.threadId = threadId;
        this.content = content;
        this.textContent = textContent;
        this.pics = pics;
        this.picFirst = picFirst;
        this.picCount = picCount;
        this.hasGif = hasGif;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPicId() {
        return picId;
    }

    public void setPicId(Long picId) {
        this.picId = picId;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getAuthorEmail() {
        return authorEmail;
    }

    public void setAuthorEmail(String authorEmail) {
        this.authorEmail = authorEmail;
    }

    public String getAuthorUrl() {
        return authorUrl;
    }

    public void setAuthorUrl(String authorUrl) {
        this.authorUrl = authorUrl;
    }

    public Timestamp getDate() {
        return date;
    }

    public void setDate(Timestamp date) {
        this.date = date;
    }

    public Long getVotePositive() {
        return votePositive;
    }

    public void setVotePositive(Long votePositive) {
        this.votePositive = votePositive;
    }

    public Long getVoteNegative() {
        return voteNegative;
    }

    public void setVoteNegative(Long voteNegative) {
        this.voteNegative = voteNegative;
    }

    public Long getCommentCount() {
        return commentCount;
    }

    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    public String getThreadId() {
        return threadId;
    }

    public void setThreadId(String threadId) {
        this.threadId = threadId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getTextContent() {
        return textContent;
    }

    public void setTextContent(String textContent) {
        this.textContent = textContent;
    }

    public String getPics() {
        return pics;
    }

    public void setPics(String pics) {
        this.pics = pics;
    }

    public String getPicFirst() {
        return picFirst;
    }

    public void setPicFirst(String picFirst) {
        this.picFirst = picFirst;
    }

    public Long getPicCount() {
        return picCount;
    }

    public void setPicCount(Long picCount) {
        this.picCount = picCount;
    }

    public Boolean getHasGif() {
        return hasGif;
    }

    public void setHasGif(Boolean hasGif) {
        this.hasGif = hasGif;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
