package info.xudshen.jandan.domain.model;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import java.sql.Timestamp;
import android.databinding.Bindable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PIC_ITEM".
 */
public class PicItem {

    private Long id;
    @Expose
    @SerializedName("comment_ID")
    private Long picId;
    @Expose
    @SerializedName("comment_author")
    private String picAuthor;
    @Expose
    @SerializedName("comment_author_email")
    private String picAuthorEmail;
    @Expose
    @SerializedName("comment_author_url")
    private String picAuthorUrl;
    @Expose
    @SerializedName("comment_date")
    private Timestamp date;
    @Expose
    private Long votePositive;
    @Expose
    private Long voteNegative;
    @Expose
    private Long commentCount;
    @Expose
    private Long commentThreadId;
    @Expose
    @SerializedName("comment_content")
    private String picContent;
    @Expose
    @SerializedName("text_content")
    private String picTextContent;
    
    private String pics;
    @Expose
    private String picFirst;
    @Expose
    private Long picCount;
    @Expose
    private Boolean hasGif;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PicItem() {
    }

    public PicItem(Long id) {
        this.id = id;
    }

    public PicItem(Long id, Long picId, String picAuthor, String picAuthorEmail, String picAuthorUrl, Timestamp date, Long votePositive, Long voteNegative, Long commentCount, Long commentThreadId, String picContent, String picTextContent, String pics, String picFirst, Long picCount, Boolean hasGif) {
        this.id = id;
        this.picId = picId;
        this.picAuthor = picAuthor;
        this.picAuthorEmail = picAuthorEmail;
        this.picAuthorUrl = picAuthorUrl;
        this.date = date;
        this.votePositive = votePositive;
        this.voteNegative = voteNegative;
        this.commentCount = commentCount;
        this.commentThreadId = commentThreadId;
        this.picContent = picContent;
        this.picTextContent = picTextContent;
        this.pics = pics;
        this.picFirst = picFirst;
        this.picCount = picCount;
        this.hasGif = hasGif;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPicId() {
        return picId;
    }

    public void setPicId(Long picId) {
        this.picId = picId;
    }

    public String getPicAuthor() {
        return picAuthor;
    }

    public void setPicAuthor(String picAuthor) {
        this.picAuthor = picAuthor;
    }

    public String getPicAuthorEmail() {
        return picAuthorEmail;
    }

    public void setPicAuthorEmail(String picAuthorEmail) {
        this.picAuthorEmail = picAuthorEmail;
    }

    public String getPicAuthorUrl() {
        return picAuthorUrl;
    }

    public void setPicAuthorUrl(String picAuthorUrl) {
        this.picAuthorUrl = picAuthorUrl;
    }

    public Timestamp getDate() {
        return date;
    }

    public void setDate(Timestamp date) {
        this.date = date;
    }

    public Long getVotePositive() {
        return votePositive;
    }

    public void setVotePositive(Long votePositive) {
        this.votePositive = votePositive;
    }

    public Long getVoteNegative() {
        return voteNegative;
    }

    public void setVoteNegative(Long voteNegative) {
        this.voteNegative = voteNegative;
    }

    public Long getCommentCount() {
        return commentCount;
    }

    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    public Long getCommentThreadId() {
        return commentThreadId;
    }

    public void setCommentThreadId(Long commentThreadId) {
        this.commentThreadId = commentThreadId;
    }

    public String getPicContent() {
        return picContent;
    }

    public void setPicContent(String picContent) {
        this.picContent = picContent;
    }

    public String getPicTextContent() {
        return picTextContent;
    }

    public void setPicTextContent(String picTextContent) {
        this.picTextContent = picTextContent;
    }

    public String getPics() {
        return pics;
    }

    public void setPics(String pics) {
        this.pics = pics;
    }

    public String getPicFirst() {
        return picFirst;
    }

    public void setPicFirst(String picFirst) {
        this.picFirst = picFirst;
    }

    public Long getPicCount() {
        return picCount;
    }

    public void setPicCount(Long picCount) {
        this.picCount = picCount;
    }

    public Boolean getHasGif() {
        return hasGif;
    }

    public void setHasGif(Boolean hasGif) {
        this.hasGif = hasGif;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
