package info.xudshen.jandan.data.model.observable;

import info.xudshen.data.BR;

import com.google.gson.annotations.Expose;
import info.xudshen.droiddata.dao.IModelObservable;
import info.xudshen.jandan.domain.enums.ReaderItemType;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import android.databinding.Bindable;

import info.xudshen.jandan.domain.model.FavoItem;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * IModelObservable<"FAVO_ITEM">
 */
public class FavoItemObservable extends android.databinding.BaseObservable  implements IModelObservable<FavoItem> {

    private Long id;
    @Expose
    private ReaderItemType type;
    @Expose
    private String actualId;
    @Expose
    private Timestamp addDate;
    @Expose
    private String url;
    @Expose
    private String title;
    @Expose
    private String excerpt;
    @Expose
    private String thumbC;
    @Expose
    private Long otherId;
    @Expose
    private String author;
    @Expose
    private String authorEmail;
    @Expose
    private String authorUrl;
    @Expose
    private Timestamp date;
    @Expose
    private Long votePositive;
    @Expose
    private Long voteNegative;
    @Expose
    private Long commentCount;
    @Expose
    private String threadId;
    @Expose
    private String content;
    @Expose
    private String textContent;
    @Expose
    private String pics;
    @Expose
    private String picFirst;
    @Expose
    private Long picCount;
    @Expose
    private Boolean hasGif;
    @Expose
    private String videoThumbnail;
    @Expose
    private String videoTitle;
    @Expose
    private String videoDescription;
    @Expose
    private Float videoDuration;
    @Expose
    private String videoLink;
    @Expose
    private String videoPlayer;
    @Expose
    private String videoSource;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FavoItemObservable() {
    }

    public FavoItemObservable(Long id) {
        this.id = id;
    }

    public FavoItemObservable(Long id, ReaderItemType type, String actualId, Timestamp addDate, String url, String title, String excerpt, String thumbC, Long otherId, String author, String authorEmail, String authorUrl, Timestamp date, Long votePositive, Long voteNegative, Long commentCount, String threadId, String content, String textContent, String pics, String picFirst, Long picCount, Boolean hasGif, String videoThumbnail, String videoTitle, String videoDescription, Float videoDuration, String videoLink, String videoPlayer, String videoSource) {
        this.id = id;
        this.type = type;
        this.actualId = actualId;
        this.addDate = addDate;
        this.url = url;
        this.title = title;
        this.excerpt = excerpt;
        this.thumbC = thumbC;
        this.otherId = otherId;
        this.author = author;
        this.authorEmail = authorEmail;
        this.authorUrl = authorUrl;
        this.date = date;
        this.votePositive = votePositive;
        this.voteNegative = voteNegative;
        this.commentCount = commentCount;
        this.threadId = threadId;
        this.content = content;
        this.textContent = textContent;
        this.pics = pics;
        this.picFirst = picFirst;
        this.picCount = picCount;
        this.hasGif = hasGif;
        this.videoThumbnail = videoThumbnail;
        this.videoTitle = videoTitle;
        this.videoDescription = videoDescription;
        this.videoDuration = videoDuration;
        this.videoLink = videoLink;
        this.videoPlayer = videoPlayer;
        this.videoSource = videoSource;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ReaderItemType getType() {
        return type;
    }

    public void setType(ReaderItemType type) {
        this.type = type;
    }

    @Bindable
    public String getActualId() {
        return actualId;
    }

    public void setActualId(String actualId) {
        if ((this.actualId == null && actualId != null)
                || (this.actualId != null && !this.actualId.equals(actualId))) {
            this.actualId = actualId;
            notifyPropertyChanged(BR.actualId);
        }
    }

    @Bindable
    public Timestamp getAddDate() {
        return addDate;
    }

    public void setAddDate(Timestamp addDate) {
        if ((this.addDate == null && addDate != null)
                || (this.addDate != null && !this.addDate.equals(addDate))) {
            this.addDate = addDate;
            notifyPropertyChanged(BR.addDate);
        }
    }

    @Bindable
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        if ((this.url == null && url != null)
                || (this.url != null && !this.url.equals(url))) {
            this.url = url;
            notifyPropertyChanged(BR.url);
        }
    }

    @Bindable
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        if ((this.title == null && title != null)
                || (this.title != null && !this.title.equals(title))) {
            this.title = title;
            notifyPropertyChanged(BR.title);
        }
    }

    @Bindable
    public String getExcerpt() {
        return excerpt;
    }

    public void setExcerpt(String excerpt) {
        if ((this.excerpt == null && excerpt != null)
                || (this.excerpt != null && !this.excerpt.equals(excerpt))) {
            this.excerpt = excerpt;
            notifyPropertyChanged(BR.excerpt);
        }
    }

    @Bindable
    public String getThumbC() {
        return thumbC;
    }

    public void setThumbC(String thumbC) {
        if ((this.thumbC == null && thumbC != null)
                || (this.thumbC != null && !this.thumbC.equals(thumbC))) {
            this.thumbC = thumbC;
            notifyPropertyChanged(BR.thumbC);
        }
    }

    @Bindable
    public Long getOtherId() {
        return otherId;
    }

    public void setOtherId(Long otherId) {
        if ((this.otherId == null && otherId != null)
                || (this.otherId != null && !this.otherId.equals(otherId))) {
            this.otherId = otherId;
            notifyPropertyChanged(BR.otherId);
        }
    }

    @Bindable
    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        if ((this.author == null && author != null)
                || (this.author != null && !this.author.equals(author))) {
            this.author = author;
            notifyPropertyChanged(BR.author);
        }
    }

    @Bindable
    public String getAuthorEmail() {
        return authorEmail;
    }

    public void setAuthorEmail(String authorEmail) {
        if ((this.authorEmail == null && authorEmail != null)
                || (this.authorEmail != null && !this.authorEmail.equals(authorEmail))) {
            this.authorEmail = authorEmail;
            notifyPropertyChanged(BR.authorEmail);
        }
    }

    @Bindable
    public String getAuthorUrl() {
        return authorUrl;
    }

    public void setAuthorUrl(String authorUrl) {
        if ((this.authorUrl == null && authorUrl != null)
                || (this.authorUrl != null && !this.authorUrl.equals(authorUrl))) {
            this.authorUrl = authorUrl;
            notifyPropertyChanged(BR.authorUrl);
        }
    }

    @Bindable
    public Timestamp getDate() {
        return date;
    }

    public void setDate(Timestamp date) {
        if ((this.date == null && date != null)
                || (this.date != null && !this.date.equals(date))) {
            this.date = date;
            notifyPropertyChanged(BR.date);
        }
    }

    @Bindable
    public Long getVotePositive() {
        return votePositive;
    }

    public void setVotePositive(Long votePositive) {
        if ((this.votePositive == null && votePositive != null)
                || (this.votePositive != null && !this.votePositive.equals(votePositive))) {
            this.votePositive = votePositive;
            notifyPropertyChanged(BR.votePositive);
        }
    }

    @Bindable
    public Long getVoteNegative() {
        return voteNegative;
    }

    public void setVoteNegative(Long voteNegative) {
        if ((this.voteNegative == null && voteNegative != null)
                || (this.voteNegative != null && !this.voteNegative.equals(voteNegative))) {
            this.voteNegative = voteNegative;
            notifyPropertyChanged(BR.voteNegative);
        }
    }

    @Bindable
    public Long getCommentCount() {
        return commentCount;
    }

    public void setCommentCount(Long commentCount) {
        if ((this.commentCount == null && commentCount != null)
                || (this.commentCount != null && !this.commentCount.equals(commentCount))) {
            this.commentCount = commentCount;
            notifyPropertyChanged(BR.commentCount);
        }
    }

    @Bindable
    public String getThreadId() {
        return threadId;
    }

    public void setThreadId(String threadId) {
        if ((this.threadId == null && threadId != null)
                || (this.threadId != null && !this.threadId.equals(threadId))) {
            this.threadId = threadId;
            notifyPropertyChanged(BR.threadId);
        }
    }

    @Bindable
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        if ((this.content == null && content != null)
                || (this.content != null && !this.content.equals(content))) {
            this.content = content;
            notifyPropertyChanged(BR.content);
        }
    }

    @Bindable
    public String getTextContent() {
        return textContent;
    }

    public void setTextContent(String textContent) {
        if ((this.textContent == null && textContent != null)
                || (this.textContent != null && !this.textContent.equals(textContent))) {
            this.textContent = textContent;
            notifyPropertyChanged(BR.textContent);
        }
    }

    @Bindable
    public String getPics() {
        return pics;
    }

    public void setPics(String pics) {
        if ((this.pics == null && pics != null)
                || (this.pics != null && !this.pics.equals(pics))) {
            this.pics = pics;
            notifyPropertyChanged(BR.pics);
        }
    }

    @Bindable
    public String getPicFirst() {
        return picFirst;
    }

    public void setPicFirst(String picFirst) {
        if ((this.picFirst == null && picFirst != null)
                || (this.picFirst != null && !this.picFirst.equals(picFirst))) {
            this.picFirst = picFirst;
            notifyPropertyChanged(BR.picFirst);
        }
    }

    @Bindable
    public Long getPicCount() {
        return picCount;
    }

    public void setPicCount(Long picCount) {
        if ((this.picCount == null && picCount != null)
                || (this.picCount != null && !this.picCount.equals(picCount))) {
            this.picCount = picCount;
            notifyPropertyChanged(BR.picCount);
        }
    }

    @Bindable
    public Boolean getHasGif() {
        return hasGif;
    }

    public void setHasGif(Boolean hasGif) {
        if ((this.hasGif == null && hasGif != null)
                || (this.hasGif != null && !this.hasGif.equals(hasGif))) {
            this.hasGif = hasGif;
            notifyPropertyChanged(BR.hasGif);
        }
    }

    @Bindable
    public String getVideoThumbnail() {
        return videoThumbnail;
    }

    public void setVideoThumbnail(String videoThumbnail) {
        if ((this.videoThumbnail == null && videoThumbnail != null)
                || (this.videoThumbnail != null && !this.videoThumbnail.equals(videoThumbnail))) {
            this.videoThumbnail = videoThumbnail;
            notifyPropertyChanged(BR.videoThumbnail);
        }
    }

    @Bindable
    public String getVideoTitle() {
        return videoTitle;
    }

    public void setVideoTitle(String videoTitle) {
        if ((this.videoTitle == null && videoTitle != null)
                || (this.videoTitle != null && !this.videoTitle.equals(videoTitle))) {
            this.videoTitle = videoTitle;
            notifyPropertyChanged(BR.videoTitle);
        }
    }

    @Bindable
    public String getVideoDescription() {
        return videoDescription;
    }

    public void setVideoDescription(String videoDescription) {
        if ((this.videoDescription == null && videoDescription != null)
                || (this.videoDescription != null && !this.videoDescription.equals(videoDescription))) {
            this.videoDescription = videoDescription;
            notifyPropertyChanged(BR.videoDescription);
        }
    }

    @Bindable
    public Float getVideoDuration() {
        return videoDuration;
    }

    public void setVideoDuration(Float videoDuration) {
        if ((this.videoDuration == null && videoDuration != null)
                || (this.videoDuration != null && !this.videoDuration.equals(videoDuration))) {
            this.videoDuration = videoDuration;
            notifyPropertyChanged(BR.videoDuration);
        }
    }

    @Bindable
    public String getVideoLink() {
        return videoLink;
    }

    public void setVideoLink(String videoLink) {
        if ((this.videoLink == null && videoLink != null)
                || (this.videoLink != null && !this.videoLink.equals(videoLink))) {
            this.videoLink = videoLink;
            notifyPropertyChanged(BR.videoLink);
        }
    }

    @Bindable
    public String getVideoPlayer() {
        return videoPlayer;
    }

    public void setVideoPlayer(String videoPlayer) {
        if ((this.videoPlayer == null && videoPlayer != null)
                || (this.videoPlayer != null && !this.videoPlayer.equals(videoPlayer))) {
            this.videoPlayer = videoPlayer;
            notifyPropertyChanged(BR.videoPlayer);
        }
    }

    @Bindable
    public String getVideoSource() {
        return videoSource;
    }

    public void setVideoSource(String videoSource) {
        if ((this.videoSource == null && videoSource != null)
                || (this.videoSource != null && !this.videoSource.equals(videoSource))) {
            this.videoSource = videoSource;
            notifyPropertyChanged(BR.videoSource);
        }
    }


    /**
     * convert entity to entityObservable
     */
    public FavoItemObservable(FavoItem entity) {
        this.id = entity.getId();
        this.type = entity.getType();
        this.actualId = entity.getActualId();
        this.addDate = entity.getAddDate();
        this.url = entity.getUrl();
        this.title = entity.getTitle();
        this.excerpt = entity.getExcerpt();
        this.thumbC = entity.getThumbC();
        this.otherId = entity.getOtherId();
        this.author = entity.getAuthor();
        this.authorEmail = entity.getAuthorEmail();
        this.authorUrl = entity.getAuthorUrl();
        this.date = entity.getDate();
        this.votePositive = entity.getVotePositive();
        this.voteNegative = entity.getVoteNegative();
        this.commentCount = entity.getCommentCount();
        this.threadId = entity.getThreadId();
        this.content = entity.getContent();
        this.textContent = entity.getTextContent();
        this.pics = entity.getPics();
        this.picFirst = entity.getPicFirst();
        this.picCount = entity.getPicCount();
        this.hasGif = entity.getHasGif();
        this.videoThumbnail = entity.getVideoThumbnail();
        this.videoTitle = entity.getVideoTitle();
        this.videoDescription = entity.getVideoDescription();
        this.videoDuration = entity.getVideoDuration();
        this.videoLink = entity.getVideoLink();
        this.videoPlayer = entity.getVideoPlayer();
        this.videoSource = entity.getVideoSource();
    }

    @Override
    public Long getModelKey() {
        return this.getId();
    }

    @Override
    public void refresh(FavoItem entity) {
        List<Integer> propertyChanges = new ArrayList<>();
        this.id = entity.getId();
        this.type = entity.getType();
        if ((this.actualId == null && entity.getActualId() != null)
                || (this.actualId != null && !this.actualId.equals(entity.getActualId()))) {
            this.actualId = entity.getActualId();
            propertyChanges.add(BR.actualId);
        }
        if ((this.addDate == null && entity.getAddDate() != null)
                || (this.addDate != null && !this.addDate.equals(entity.getAddDate()))) {
            this.addDate = entity.getAddDate();
            propertyChanges.add(BR.addDate);
        }
        if ((this.url == null && entity.getUrl() != null)
                || (this.url != null && !this.url.equals(entity.getUrl()))) {
            this.url = entity.getUrl();
            propertyChanges.add(BR.url);
        }
        if ((this.title == null && entity.getTitle() != null)
                || (this.title != null && !this.title.equals(entity.getTitle()))) {
            this.title = entity.getTitle();
            propertyChanges.add(BR.title);
        }
        if ((this.excerpt == null && entity.getExcerpt() != null)
                || (this.excerpt != null && !this.excerpt.equals(entity.getExcerpt()))) {
            this.excerpt = entity.getExcerpt();
            propertyChanges.add(BR.excerpt);
        }
        if ((this.thumbC == null && entity.getThumbC() != null)
                || (this.thumbC != null && !this.thumbC.equals(entity.getThumbC()))) {
            this.thumbC = entity.getThumbC();
            propertyChanges.add(BR.thumbC);
        }
        if ((this.otherId == null && entity.getOtherId() != null)
                || (this.otherId != null && !this.otherId.equals(entity.getOtherId()))) {
            this.otherId = entity.getOtherId();
            propertyChanges.add(BR.otherId);
        }
        if ((this.author == null && entity.getAuthor() != null)
                || (this.author != null && !this.author.equals(entity.getAuthor()))) {
            this.author = entity.getAuthor();
            propertyChanges.add(BR.author);
        }
        if ((this.authorEmail == null && entity.getAuthorEmail() != null)
                || (this.authorEmail != null && !this.authorEmail.equals(entity.getAuthorEmail()))) {
            this.authorEmail = entity.getAuthorEmail();
            propertyChanges.add(BR.authorEmail);
        }
        if ((this.authorUrl == null && entity.getAuthorUrl() != null)
                || (this.authorUrl != null && !this.authorUrl.equals(entity.getAuthorUrl()))) {
            this.authorUrl = entity.getAuthorUrl();
            propertyChanges.add(BR.authorUrl);
        }
        if ((this.date == null && entity.getDate() != null)
                || (this.date != null && !this.date.equals(entity.getDate()))) {
            this.date = entity.getDate();
            propertyChanges.add(BR.date);
        }
        if ((this.votePositive == null && entity.getVotePositive() != null)
                || (this.votePositive != null && !this.votePositive.equals(entity.getVotePositive()))) {
            this.votePositive = entity.getVotePositive();
            propertyChanges.add(BR.votePositive);
        }
        if ((this.voteNegative == null && entity.getVoteNegative() != null)
                || (this.voteNegative != null && !this.voteNegative.equals(entity.getVoteNegative()))) {
            this.voteNegative = entity.getVoteNegative();
            propertyChanges.add(BR.voteNegative);
        }
        if ((this.commentCount == null && entity.getCommentCount() != null)
                || (this.commentCount != null && !this.commentCount.equals(entity.getCommentCount()))) {
            this.commentCount = entity.getCommentCount();
            propertyChanges.add(BR.commentCount);
        }
        if ((this.threadId == null && entity.getThreadId() != null)
                || (this.threadId != null && !this.threadId.equals(entity.getThreadId()))) {
            this.threadId = entity.getThreadId();
            propertyChanges.add(BR.threadId);
        }
        if ((this.content == null && entity.getContent() != null)
                || (this.content != null && !this.content.equals(entity.getContent()))) {
            this.content = entity.getContent();
            propertyChanges.add(BR.content);
        }
        if ((this.textContent == null && entity.getTextContent() != null)
                || (this.textContent != null && !this.textContent.equals(entity.getTextContent()))) {
            this.textContent = entity.getTextContent();
            propertyChanges.add(BR.textContent);
        }
        if ((this.pics == null && entity.getPics() != null)
                || (this.pics != null && !this.pics.equals(entity.getPics()))) {
            this.pics = entity.getPics();
            propertyChanges.add(BR.pics);
        }
        if ((this.picFirst == null && entity.getPicFirst() != null)
                || (this.picFirst != null && !this.picFirst.equals(entity.getPicFirst()))) {
            this.picFirst = entity.getPicFirst();
            propertyChanges.add(BR.picFirst);
        }
        if ((this.picCount == null && entity.getPicCount() != null)
                || (this.picCount != null && !this.picCount.equals(entity.getPicCount()))) {
            this.picCount = entity.getPicCount();
            propertyChanges.add(BR.picCount);
        }
        if ((this.hasGif == null && entity.getHasGif() != null)
                || (this.hasGif != null && !this.hasGif.equals(entity.getHasGif()))) {
            this.hasGif = entity.getHasGif();
            propertyChanges.add(BR.hasGif);
        }
        if ((this.videoThumbnail == null && entity.getVideoThumbnail() != null)
                || (this.videoThumbnail != null && !this.videoThumbnail.equals(entity.getVideoThumbnail()))) {
            this.videoThumbnail = entity.getVideoThumbnail();
            propertyChanges.add(BR.videoThumbnail);
        }
        if ((this.videoTitle == null && entity.getVideoTitle() != null)
                || (this.videoTitle != null && !this.videoTitle.equals(entity.getVideoTitle()))) {
            this.videoTitle = entity.getVideoTitle();
            propertyChanges.add(BR.videoTitle);
        }
        if ((this.videoDescription == null && entity.getVideoDescription() != null)
                || (this.videoDescription != null && !this.videoDescription.equals(entity.getVideoDescription()))) {
            this.videoDescription = entity.getVideoDescription();
            propertyChanges.add(BR.videoDescription);
        }
        if ((this.videoDuration == null && entity.getVideoDuration() != null)
                || (this.videoDuration != null && !this.videoDuration.equals(entity.getVideoDuration()))) {
            this.videoDuration = entity.getVideoDuration();
            propertyChanges.add(BR.videoDuration);
        }
        if ((this.videoLink == null && entity.getVideoLink() != null)
                || (this.videoLink != null && !this.videoLink.equals(entity.getVideoLink()))) {
            this.videoLink = entity.getVideoLink();
            propertyChanges.add(BR.videoLink);
        }
        if ((this.videoPlayer == null && entity.getVideoPlayer() != null)
                || (this.videoPlayer != null && !this.videoPlayer.equals(entity.getVideoPlayer()))) {
            this.videoPlayer = entity.getVideoPlayer();
            propertyChanges.add(BR.videoPlayer);
        }
        if ((this.videoSource == null && entity.getVideoSource() != null)
                || (this.videoSource != null && !this.videoSource.equals(entity.getVideoSource()))) {
            this.videoSource = entity.getVideoSource();
            propertyChanges.add(BR.videoSource);
        }

        if (propertyChanges.size() == 1) {
            notifyPropertyChanged(propertyChanges.get(0));
        } else if (propertyChanges.size() > 1) {
            notifyChange();
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
