package info.xudshen.jandan.data.model.observable;

import info.xudshen.data.BR;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import info.xudshen.droiddata.dao.IModelObservable;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import android.databinding.Bindable;

import info.xudshen.jandan.domain.model.PicComment;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * IModelObservable<"PIC_COMMENT">
 */
public class PicCommentObservable extends android.databinding.BaseObservable  implements IModelObservable<PicComment> {

    private Long id;
    @Expose
    @SerializedName("post_id")
    private String picCommentId;
    @Expose
    @SerializedName("thread_id")
    private String picThreadId;
    @Expose
    private String picThreadKey;
    @Expose
    private String message;
    @Expose
    @SerializedName("created_at")
    private Timestamp date;
    @Expose
    @SerializedName("parent_id")
    private String parentCommentId;
    @Expose
    private String authorId;
    @Expose
    private String authorName;
    @Expose
    private String authorAvatar;
    @Expose
    private String authorUrl;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PicCommentObservable() {
    }

    public PicCommentObservable(Long id) {
        this.id = id;
    }

    public PicCommentObservable(Long id, String picCommentId, String picThreadId, String picThreadKey, String message, Timestamp date, String parentCommentId, String authorId, String authorName, String authorAvatar, String authorUrl) {
        this.id = id;
        this.picCommentId = picCommentId;
        this.picThreadId = picThreadId;
        this.picThreadKey = picThreadKey;
        this.message = message;
        this.date = date;
        this.parentCommentId = parentCommentId;
        this.authorId = authorId;
        this.authorName = authorName;
        this.authorAvatar = authorAvatar;
        this.authorUrl = authorUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Bindable
    public String getPicCommentId() {
        return picCommentId;
    }

    public void setPicCommentId(String picCommentId) {
        if ((this.picCommentId == null && picCommentId != null)
                || (this.picCommentId != null && !this.picCommentId.equals(picCommentId))) {
            this.picCommentId = picCommentId;
            notifyPropertyChanged(BR.picCommentId);
        }
    }

    @Bindable
    public String getPicThreadId() {
        return picThreadId;
    }

    public void setPicThreadId(String picThreadId) {
        if ((this.picThreadId == null && picThreadId != null)
                || (this.picThreadId != null && !this.picThreadId.equals(picThreadId))) {
            this.picThreadId = picThreadId;
            notifyPropertyChanged(BR.picThreadId);
        }
    }

    @Bindable
    public String getPicThreadKey() {
        return picThreadKey;
    }

    public void setPicThreadKey(String picThreadKey) {
        if ((this.picThreadKey == null && picThreadKey != null)
                || (this.picThreadKey != null && !this.picThreadKey.equals(picThreadKey))) {
            this.picThreadKey = picThreadKey;
            notifyPropertyChanged(BR.picThreadKey);
        }
    }

    @Bindable
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        if ((this.message == null && message != null)
                || (this.message != null && !this.message.equals(message))) {
            this.message = message;
            notifyPropertyChanged(BR.message);
        }
    }

    @Bindable
    public Timestamp getDate() {
        return date;
    }

    public void setDate(Timestamp date) {
        if ((this.date == null && date != null)
                || (this.date != null && !this.date.equals(date))) {
            this.date = date;
            notifyPropertyChanged(BR.date);
        }
    }

    @Bindable
    public String getParentCommentId() {
        return parentCommentId;
    }

    public void setParentCommentId(String parentCommentId) {
        if ((this.parentCommentId == null && parentCommentId != null)
                || (this.parentCommentId != null && !this.parentCommentId.equals(parentCommentId))) {
            this.parentCommentId = parentCommentId;
            notifyPropertyChanged(BR.parentCommentId);
        }
    }

    @Bindable
    public String getAuthorId() {
        return authorId;
    }

    public void setAuthorId(String authorId) {
        if ((this.authorId == null && authorId != null)
                || (this.authorId != null && !this.authorId.equals(authorId))) {
            this.authorId = authorId;
            notifyPropertyChanged(BR.authorId);
        }
    }

    @Bindable
    public String getAuthorName() {
        return authorName;
    }

    public void setAuthorName(String authorName) {
        if ((this.authorName == null && authorName != null)
                || (this.authorName != null && !this.authorName.equals(authorName))) {
            this.authorName = authorName;
            notifyPropertyChanged(BR.authorName);
        }
    }

    @Bindable
    public String getAuthorAvatar() {
        return authorAvatar;
    }

    public void setAuthorAvatar(String authorAvatar) {
        if ((this.authorAvatar == null && authorAvatar != null)
                || (this.authorAvatar != null && !this.authorAvatar.equals(authorAvatar))) {
            this.authorAvatar = authorAvatar;
            notifyPropertyChanged(BR.authorAvatar);
        }
    }

    @Bindable
    public String getAuthorUrl() {
        return authorUrl;
    }

    public void setAuthorUrl(String authorUrl) {
        if ((this.authorUrl == null && authorUrl != null)
                || (this.authorUrl != null && !this.authorUrl.equals(authorUrl))) {
            this.authorUrl = authorUrl;
            notifyPropertyChanged(BR.authorUrl);
        }
    }


    /**
     * convert entity to entityObservable
     */
    public PicCommentObservable(PicComment entity) {
        this.id = entity.getId();
        this.picCommentId = entity.getPicCommentId();
        this.picThreadId = entity.getPicThreadId();
        this.picThreadKey = entity.getPicThreadKey();
        this.message = entity.getMessage();
        this.date = entity.getDate();
        this.parentCommentId = entity.getParentCommentId();
        this.authorId = entity.getAuthorId();
        this.authorName = entity.getAuthorName();
        this.authorAvatar = entity.getAuthorAvatar();
        this.authorUrl = entity.getAuthorUrl();
    }

    @Override
    public Long getModelKey() {
        return this.getId();
    }

    @Override
    public void refresh(PicComment entity) {
        List<Integer> propertyChanges = new ArrayList<>();
        this.id = entity.getId();
        if ((this.picCommentId == null && entity.getPicCommentId() != null)
                || (this.picCommentId != null && !this.picCommentId.equals(entity.getPicCommentId()))) {
            this.picCommentId = entity.getPicCommentId();
            propertyChanges.add(BR.picCommentId);
        }
        if ((this.picThreadId == null && entity.getPicThreadId() != null)
                || (this.picThreadId != null && !this.picThreadId.equals(entity.getPicThreadId()))) {
            this.picThreadId = entity.getPicThreadId();
            propertyChanges.add(BR.picThreadId);
        }
        if ((this.picThreadKey == null && entity.getPicThreadKey() != null)
                || (this.picThreadKey != null && !this.picThreadKey.equals(entity.getPicThreadKey()))) {
            this.picThreadKey = entity.getPicThreadKey();
            propertyChanges.add(BR.picThreadKey);
        }
        if ((this.message == null && entity.getMessage() != null)
                || (this.message != null && !this.message.equals(entity.getMessage()))) {
            this.message = entity.getMessage();
            propertyChanges.add(BR.message);
        }
        if ((this.date == null && entity.getDate() != null)
                || (this.date != null && !this.date.equals(entity.getDate()))) {
            this.date = entity.getDate();
            propertyChanges.add(BR.date);
        }
        if ((this.parentCommentId == null && entity.getParentCommentId() != null)
                || (this.parentCommentId != null && !this.parentCommentId.equals(entity.getParentCommentId()))) {
            this.parentCommentId = entity.getParentCommentId();
            propertyChanges.add(BR.parentCommentId);
        }
        if ((this.authorId == null && entity.getAuthorId() != null)
                || (this.authorId != null && !this.authorId.equals(entity.getAuthorId()))) {
            this.authorId = entity.getAuthorId();
            propertyChanges.add(BR.authorId);
        }
        if ((this.authorName == null && entity.getAuthorName() != null)
                || (this.authorName != null && !this.authorName.equals(entity.getAuthorName()))) {
            this.authorName = entity.getAuthorName();
            propertyChanges.add(BR.authorName);
        }
        if ((this.authorAvatar == null && entity.getAuthorAvatar() != null)
                || (this.authorAvatar != null && !this.authorAvatar.equals(entity.getAuthorAvatar()))) {
            this.authorAvatar = entity.getAuthorAvatar();
            propertyChanges.add(BR.authorAvatar);
        }
        if ((this.authorUrl == null && entity.getAuthorUrl() != null)
                || (this.authorUrl != null && !this.authorUrl.equals(entity.getAuthorUrl()))) {
            this.authorUrl = entity.getAuthorUrl();
            propertyChanges.add(BR.authorUrl);
        }

        if (propertyChanges.size() == 1) {
            notifyPropertyChanged(propertyChanges.get(0));
        } else if (propertyChanges.size() > 1) {
            notifyChange();
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
