package info.xudshen.jandan.data.model.observable;

import info.xudshen.data.BR;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import info.xudshen.droiddata.dao.IModelObservable;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import android.databinding.Bindable;

import info.xudshen.jandan.domain.model.SimplePost;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * IModelObservable<"SIMPLE_POST">
 */
public class SimplePostObservable extends android.databinding.BaseObservable  implements IModelObservable<SimplePost> {

    private Long id;
    @Expose
    @SerializedName("id")
    private Long postId;
    @Expose
    private String url;
    @Expose
    private String title;
    @Expose
    private String excerpt;
    @Expose
    private String thumbC;
    @Expose
    private Timestamp date;
    @Expose
    private Timestamp modified;
    @Expose
    private String commentCount;
    @Expose
    private String authorName;
    @Expose
    private String categoryDescription;
    @Expose
    private String expireTag;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SimplePostObservable() {
    }

    public SimplePostObservable(Long id) {
        this.id = id;
    }

    public SimplePostObservable(Long id, Long postId, String url, String title, String excerpt, String thumbC, Timestamp date, Timestamp modified, String commentCount, String authorName, String categoryDescription, String expireTag) {
        this.id = id;
        this.postId = postId;
        this.url = url;
        this.title = title;
        this.excerpt = excerpt;
        this.thumbC = thumbC;
        this.date = date;
        this.modified = modified;
        this.commentCount = commentCount;
        this.authorName = authorName;
        this.categoryDescription = categoryDescription;
        this.expireTag = expireTag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Bindable
    public Long getPostId() {
        return postId;
    }

    public void setPostId(Long postId) {
        if ((this.postId == null && postId != null)
                || (this.postId != null && !this.postId.equals(postId))) {
            this.postId = postId;
            notifyPropertyChanged(BR.postId);
        }
    }

    @Bindable
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        if ((this.url == null && url != null)
                || (this.url != null && !this.url.equals(url))) {
            this.url = url;
            notifyPropertyChanged(BR.url);
        }
    }

    @Bindable
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        if ((this.title == null && title != null)
                || (this.title != null && !this.title.equals(title))) {
            this.title = title;
            notifyPropertyChanged(BR.title);
        }
    }

    @Bindable
    public String getExcerpt() {
        return excerpt;
    }

    public void setExcerpt(String excerpt) {
        if ((this.excerpt == null && excerpt != null)
                || (this.excerpt != null && !this.excerpt.equals(excerpt))) {
            this.excerpt = excerpt;
            notifyPropertyChanged(BR.excerpt);
        }
    }

    @Bindable
    public String getThumbC() {
        return thumbC;
    }

    public void setThumbC(String thumbC) {
        if ((this.thumbC == null && thumbC != null)
                || (this.thumbC != null && !this.thumbC.equals(thumbC))) {
            this.thumbC = thumbC;
            notifyPropertyChanged(BR.thumbC);
        }
    }

    public Timestamp getDate() {
        return date;
    }

    public void setDate(Timestamp date) {
        this.date = date;
    }

    public Timestamp getModified() {
        return modified;
    }

    public void setModified(Timestamp modified) {
        this.modified = modified;
    }

    public String getCommentCount() {
        return commentCount;
    }

    public void setCommentCount(String commentCount) {
        this.commentCount = commentCount;
    }

    public String getAuthorName() {
        return authorName;
    }

    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    public String getCategoryDescription() {
        return categoryDescription;
    }

    public void setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription;
    }

    public String getExpireTag() {
        return expireTag;
    }

    public void setExpireTag(String expireTag) {
        this.expireTag = expireTag;
    }


    /**
     * convert entity to entityObservable
     */
    public SimplePostObservable(SimplePost entity) {
        this.id = entity.getId();
        this.postId = entity.getPostId();
        this.url = entity.getUrl();
        this.title = entity.getTitle();
        this.excerpt = entity.getExcerpt();
        this.thumbC = entity.getThumbC();
        this.date = entity.getDate();
        this.modified = entity.getModified();
        this.commentCount = entity.getCommentCount();
        this.authorName = entity.getAuthorName();
        this.categoryDescription = entity.getCategoryDescription();
        this.expireTag = entity.getExpireTag();
    }

    @Override
    public Long getModelKey() {
        return this.getId();
    }

    @Override
    public void refresh(SimplePost entity) {
        List<Integer> propertyChanges = new ArrayList<>();
        this.id = entity.getId();
        if ((this.postId == null && entity.getPostId() != null)
                || (this.postId != null && !this.postId.equals(entity.getPostId()))) {
            this.postId = entity.getPostId();
            propertyChanges.add(BR.postId);
        }
        if ((this.url == null && entity.getUrl() != null)
                || (this.url != null && !this.url.equals(entity.getUrl()))) {
            this.url = entity.getUrl();
            propertyChanges.add(BR.url);
        }
        if ((this.title == null && entity.getTitle() != null)
                || (this.title != null && !this.title.equals(entity.getTitle()))) {
            this.title = entity.getTitle();
            propertyChanges.add(BR.title);
        }
        if ((this.excerpt == null && entity.getExcerpt() != null)
                || (this.excerpt != null && !this.excerpt.equals(entity.getExcerpt()))) {
            this.excerpt = entity.getExcerpt();
            propertyChanges.add(BR.excerpt);
        }
        if ((this.thumbC == null && entity.getThumbC() != null)
                || (this.thumbC != null && !this.thumbC.equals(entity.getThumbC()))) {
            this.thumbC = entity.getThumbC();
            propertyChanges.add(BR.thumbC);
        }
        this.date = entity.getDate();
        this.modified = entity.getModified();
        this.commentCount = entity.getCommentCount();
        this.authorName = entity.getAuthorName();
        this.categoryDescription = entity.getCategoryDescription();
        this.expireTag = entity.getExpireTag();

        if (propertyChanges.size() == 1) {
            notifyPropertyChanged(propertyChanges.get(0));
        } else if (propertyChanges.size() > 1) {
            notifyChange();
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
